[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/github/jnr/jffi/1.2.18/jffi-1.2.18-native.jar: wrong checksum: C:\Users\Adlet\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\jnr\jffi\1.2.18\jffi-1.2.18-native.jar (expected SHA-1 fb54851e631ff91651762587bc3c61a407d328df in C:\Users\Adlet\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\jnr\jffi\1.2.18\.jffi-1.2.18-native.jar__sha1, got aa51b75aef193f059435c4f64e177d2ca32bd89)
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:346)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:84)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$WrongChecksum: wrong checksum: C:\Users\Adlet\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\jnr\jffi\1.2.18\jffi-1.2.18-native.jar (expected SHA-1 fb54851e631ff91651762587bc3c61a407d328df in C:\Users\Adlet\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\jnr\jffi\1.2.18\.jffi-1.2.18-native.jar__sha1, got aa51b75aef193f059435c4f64e177d2ca32bd89)
[error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$validateChecksum$4(FileCache.scala:694)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] (ssExtractDependencies) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://repo1.maven.org/maven2/com/github/jnr/jffi/1.2.18/jffi-1.2.18-native.jar: wrong checksum: C:\Users\Adlet\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\jnr\jffi\1.2.18\jffi-1.2.18-native.jar (expected SHA-1 fb54851e631ff91651762587bc3c61a407d328df in C:\Users\Adlet\AppData\Local\Coursier\cache\v1\https\repo1.maven.org\maven2\com\github\jnr\jffi\1.2.18\.jffi-1.2.18-native.jar__sha1, got aa51b75aef193f059435c4f64e177d2ca32bd89)
